### ISSUE TITLE
cibseven-webclient with Basic Authentication for REST API enabled

### ISSUE THREAD

**Issue by Johannes-** [cibseven/cibseven-webclient#277]
Hi,

Is it possible to configure the Webclient to work with the Camunda REST API when Basic Authentication is enabled? I've reviewed the documentation but haven't found any information regarding this specific configuration.

Best regards

**Comment by amardeep2006** [comment]
Thanks for the clarification. I was able to run it with few changes in your configs

1. Authentication changed to composite. I feel there is need to update this in CIB documentation.
2. The engine rest url does not need credentials as it makes use of JWT for user authentication.

```yaml
services:
  cibseven:
    image: cibseven/cibseven:run-2.0.0
    ports:
      - "8080:8080"
    environment:
      CAMUNDA_BPM_RUN_AUTH_AUTHENTICATION: "composite"
      CAMUNDA_BPM_RUN_AUTH_ENABLED: "true"
      CIBSEVEN_WEBCLIENT_ENGINEREST_URL: http://localhost:8080
      DEBUG: "true"
```
